name: tldr
version: '0.9.2'
synopsis: Haskell tldr client
description: |
  Haskell tldr client with support for viewing tldr pages. Has offline
  cache for accessing pages. Visit https://tldr.sh for more details.
category: Web, CLI
author: Sibi Prabakaran
maintainer: sibi@psibi.in
copyright: 2017 Sibi Prabakaran
license: BSD3
github: psibi/tldr-hs

extra-source-files:
- README.md
- CHANGELOG.md
- test/data/*.golden
- test/data/*.md

flags:
  static:
    description: Statically link executables.
    manual: true
    default: false

library:
  source-dirs: src
  dependencies:
  - attoparsec
  - base >=4.7 && <5
  - cmark
  - text
  - bytestring
  - ansi-terminal
  - optparse-applicative
  - directory
  - filepath
  - semigroups
  - containers
  - http-conduit
  - zip-archive
  - time

ghc-options:
  - -Wall
  - -O2

executables:
  tldr:
    main: Main.hs
    source-dirs: app
    when:
      - condition: flag(static) && os(linux)
        then:
          ld-options: -static
          ghc-options: "-rtsopts -threaded -optc-Os -optl=-pthread -optl=-static -fPIC"
        else:
          ghc-options: "-rtsopts -threaded"
    dependencies:
    - base
    - tldr

tests:
  tldr-test:
    main: Spec.hs
    source-dirs: test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - base
    - tldr
    - process
    - tasty
    - tasty-golden
    - tasty-hunit
#    - tasty-quickcheck
